# ESS Game

An Attacker-Defender game involves two players: an attacker who moves pieces, and a defender who destroys
pieces. An instance of the game has a set of levels numbered from 0 to K, and N pieces that are initialized across
these levels. The attacker’s goal is to get at least one of their
pieces to level K, and the defender’s goal is to destroy all
N pieces before this can happen. 

- In each turn, the attacker proposes a partition A, B of the pieces still in play. 
- The defender then chooses one of the sets to destroy and remove from play. 
- All pieces in the other set are moved up a level.

The game ends when either one or more pieces reach level K, or when all pieces are destroyed

In [11]:
import numpy as np
import random

class ESS_GAME():
    def __init__(self, levels, nb_pieces):
        
        self.levels = levels
        self.nb_pieces = nb_pieces
        self.width = 5
        self.board = np.zeros((self.levels, self.width))
        
        self.coordinates = [(random.randrange(0, self.levels), random.randrange(0, self.width)) for i in range(self.nb_pieces)] #generate y,x coordinate
        
        for y, x in (self.coordinates):
            self.board[y, x] = 1 #assign coordinates to board
        
    def play(self):
        
        print('initial-board')
        print(self.board)
        print('\n')
        
        while sum(self.board[0]) < 1:
        
            ### split
            
            if len(self.coordinates) > 1:
            
                m = np.random.randint(low = 1, high = len(self.coordinates))
            
            else:
                
                self.board[self.coordinates] = 0
                
                print('There is only one point left, thus it will be destroyed - defender wins !')
                print('\n') 
                
                break
            
            coo_left = random.choices(self.coordinates, k=m)
            
            #s = set(coo_left)
            
            coo_right = [x for x in self.coordinates if x not in coo_left] #every coordinate not in coo_left
            
            print('coordinates-left-chunk')
            print(coo_left)
            print('\n') 
    
            print('coordinates-right-chunk')
            print(coo_right)
            print('\n')

            ### choose what to destroy
            
            chosen_one = np.random.randint(low = 0, high = 2)
            
            if chosen_one == 0:
                
                for y_, x_ in (coo_right):
                    self.board[y_, x_] = 0
                    
                print('left was chosen to be kept')
                print('\n')
                
            else:
                
                for y_, x_ in (coo_left):
                    self.board[y_, x_] = 0
                    
                print('right was chosen to be kept')
                print('\n')

            ### up

            self.board = np.roll(self.board, -self.width)
            
            print('new-board')
            print(self.board)
            print('\n')
            
            self.coordinates = np.argwhere(self.board).tolist()
                  
        #print('attacker wins')
        print('final-board')
        print(self.board)

In [20]:
game = ESS_GAME(levels=10, nb_pieces = 5)

In [21]:
game.play()

initial-board
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


coordinates-left-chunk
[(2, 0), (4, 1), (3, 4)]


coordinates-right-chunk
[(5, 0), (3, 1)]


left was chosen to be kept


new-board
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


coordinates-left-chunk
[[1, 0], [3, 1]]


coordinates-right-chunk
[[2, 4]]


right was chosen to be kept


new-board
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


There is only one point left, thus it will be destroyed - defender wins !


final-board
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0.

C:\Users\Adrien\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
