# ESS Game

An Attacker-Defender game involves two players: an attacker who moves pieces, and a defender who destroys
pieces. An instance of the game has a set of levels numbered from 0 to K, and N pieces that are initialized across
these levels. The attacker’s goal is to get at least one of their
pieces to level K, and the defender’s goal is to destroy all
N pieces before this can happen. 

- In each turn, the attacker proposes a partition A, B of the pieces still in play. 
- The defender then chooses one of the sets to destroy and remove from play. 
- All pieces in the other set are moved up a level.

The game ends when either one or more pieces reach level K, or when all pieces are destroyed

In [16]:
import numpy as np
import random

class ESS_GAME():
    def __init__(self, levels, nb_pieces):
        
        self.levels = levels
        self.nb_pieces = nb_pieces
        self.width = 5
        self.board = np.zeros((self.levels, self.width))
        
        self.coordinates = [(random.randrange(0, self.levels), random.randrange(0, self.width)) for i in range(self.nb_pieces)]
        
        for y, x in (self.coordinates):
            self.board[y, x] = 1
        
    def play(self):
        
        print('initial-board')
        print(self.board)
        print('\n')
        
        while sum(self.board[0]) != 1:
        
            ### split
            
            n = np.random.randint(low = 1, high = len(self.board)-1)
            index = np.sort(np.random.choice(self.board.shape[0], n, replace=False))
            
            others_indexes = np.delete(np.arange(len(self.board)), index)
            
            left = self.board[index]
            right = self.board[others_indexes]
            
            print('left-chunk')
            print(left)
            print('\n')
            print('right-chunk')
            print(right)
            print('\n')

            ### choose what to destroy
            
            chosen_one = np.random.randint(low = 0, high = 2)
            
            if chosen_one == 0:
                
                self.board[index] = 0
                
            else:
                
                self.board[others_indexes] = 0 
            
            print('board')
            print(self.board)
            print('\n')

            ### up

            self.board = np.roll(self.board, -self.width)
            
            if np.count_nonzero(self.board) == 0:
                
                print('defender wins')
                
                break
                  
        #print('attacker wins')
        print(self.board)

In [17]:
game = ESS_GAME(levels=10, nb_pieces = 5)

In [18]:
game.play()

initial-board
[[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


left-chunk
[[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


right-chunk
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


board
[[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


left-chunk
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


right-chunk
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


board
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]


left-ch